### PR TITLE
Move charging station

### PR DESCRIPTION
**Pull request by Ninjeneer**
Still need a translation for ES / DE / PT

### CODE REVIEW

**Comment by jerome-benoit** [comment]
The feature to have a UI to easily move charging stations from one site area to another have been requested by at least 3 customers: they do the integration and configuration at their desk then ship the charging station to the destination site area, install and validate it, create the target site area and then move the station to the target site area.

**Comment by LucasBrazi06** [comment]
> The feature to have a UI to easily move charging stations from one site area to another have been requested by at least 3 customers: they do the integration and configuration at their desk then ship the charging station to the destination site area, install and validate it, create the target site area and then move the station to the target site area.

Edit Charging Station > change the Site Area > Save ?

**Comment by jerome-benoit** [comment]
> > It's a counter intuitive user experience design, the action is not explicit.
> 
> Okay, I think we have at least a work around that we can explain to the customer.

We (Kinza, Gerald and I) will redirect the support flow generated by counter intuitive user experience design directly to you in the meantime :)

**Comment by LucasBrazi06** [comment]
> We (Kinza, Gerald and I) will redirect the support flow generated by counter intuitive user experience design directly to you in the meantime :)

Okay, I will discuss with them then :-)

**Pull request closed without merging**
