### PR TITLE
Billing - stripe UI list payment methods - DRAFT

### PR DESCRIPTION
**Pull request by ClaudeROSSI**

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI This one is to merge?
Because not attached to an issue.

**Comment by ClaudeROSSI** [comment]
Ne touche a rien … j’essai de recup les modifs de Caro !

From: FABIANO Serge ***@***.***>
Reply to: sap-labs-france/ev-dashboard ***@***.***>
Date: Friday 19 March 2021 at 22:34
To: sap-labs-france/ev-dashboard ***@***.***>
Cc: Claude ROSSI ***@***.***>, Mention ***@***.***>
Subject: Re: [sap-labs-france/ev-dashboard] Billing - stripe UI list payment methods (#2310)


@ClaudeROSSI<https://github.com/ClaudeROSSI> This one is to merge?
Because not attached to an issue.

**Comment by ClaudeROSSI** [comment]
> @ClaudeROSSI This one is to merge?
> Because not attached to an issue.

We have a merge conflict that we couldn't solve!
I'll create a new branch with a cleean history and then we will get rid of this one.

**Comment by ClaudeROSSI** [comment]
All changes are now in a diffrent branch.

Closing this one

**Pull request closed without merging**
