### PR TITLE
Maximum Amperage not taking number of phases into account

### PR DESCRIPTION
**Pull request by guido4096**
The maximum amperage should be divided by the number of phases.

### CODE REVIEW

**Comment by guido4096** [comment]
Dear, I've been exploring your EV backend solution and would like to contribute a fix for a bug. It is a fairly simple and cosmetic bug. This allows me to experience how contributing to your code base works and allows to get to know each other. Regards, Guido

**Comment by guido4096** [comment]
#2926

**Review by LucasBrazi06 — COMMENTED** [review]
Thanks for your PR!
We don't want the amperage per phase here but the total amperage that the side can support.
The number of phases is taken into account in the Smart Charging algorithm during the creation of the charging plans.

**Comment by guido4096** [comment]
Thanks for your reply. I'm a bit confused, I must misinterpret something. If I read in that dialog "Maximum Power", I interpret that as the "Maximum Power" delivered by that site area. And that is the power delivered of course by all phases that are present. For example, if a charging station manufacturer company claims a charging station can deliver 22 KW of power, this is over all 3 phases combined, with an amperage of 32 A. 

If you look at the current dialog, you can see following 4 values together:

- Phase/Neutral Voltage: 230 V
- Maximum Power: 22000 W
- Number of phases: Three phases
- Maximum Amperage: 95 A

These 4 values just don't match up well, not in my head at least and I think also not in the head of somebody responsible for the electrical installation. Finally, the maximum amperage is only an online calculated and visible value, this is not stored anywhere, unless I overlook something?

**Comment by LucasBrazi06** [comment]
> These 4 values just don't match up well, not in my head at least and I think also not in the head of somebody responsible for the electrical installation. Finally, the maximum amperage is only an online calculated and visible value, this is not stored anywhere, unless I overlook something?

I totally agree, usually electricians always deal with amps per phase.
We can improve the label and say 'all combined phases' or something approaching?
Feel free to propose something less confusing also :-)
Yes, this input field is just an informative read only value not saved in the DB.

**Comment by guido4096** [comment]
To make it clear, a text like "Maximum amperage if all power would be delivered by a single phase with the indicated voltage". I myself find such long text awkward. Instead I would then propose to remove the field completely: if it takes so much text to explain what the value means, it means the value is confusing and might not help the end user?

**Comment by LucasBrazi06** [comment]
> To make it clear, a text like "Maximum amperage if all power would be delivered by a single phase with the indicated voltage". I myself find such long text awkward. Instead I would then propose to remove the field completely: if it takes so much text to explain what the value means, it means the value is confusing and might not help the end user?

We had the same issue with the Charging Station's connectors :-).
And we put both amperage values:


For me, it helped in having a rough idea on what would be the max amps supported.
Because when you talk of power, you always talk about the total power regardless the number of phases. We never say 1000 Watts / Phase and this was the purpose of these fields (amps/phase and  total amps) to talk to the experts as well as the human beings.
Maybe we could add both fields?

**Comment by guido4096** [comment]
that would work, nice solution, thanks. Are you ok if I prepare changes in a new PR, with the layout like below? not sure I can work on this today, hopefully by tomorrow. 

image

**Comment by LucasBrazi06** [comment]
> that would work, nice solution, thanks. Are you ok if I prepare changes in a new PR, with the layout like below? not sure I can work on this today, hopefully by tomorrow.

Yes it would be great!
No problem, take your time ;-)

**Comment by guido4096** [comment]
> @guido4096,
> If you are interested in contributing, I can add you in the contributor users.
> Let me know.
@LucasBrazi06 yes, I would like to contribute, if you can add me to the contributors list, that would be great.

**Comment by guido4096** [comment]
@LucasBrazi06 how to deal with these eslint errors? I can fix them, just not sure on the direction to fix. 

- the uppercase enum values, I believe they should be ignored by eslint, the values seem to be used as strings, changing case looks dangerous
- the error in test.ts I also think it should be ignored as it is just declaring what is reused from somwhere else
- the error in log-actions-dialog.component.ts can be fixed by renaming the local variable
- the warnings about handling Promises, the 3 cases that are triggered should be fine to treat them as void

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 how to deal with these eslint errors? I can fix them, just not sure on the direction to fix.

I fixed some of them (wrong naming due to refactoring of misnamed usage).
You can ignore test.js errors indeed.
Try to resync your branch with master-qa and let me know.
Thanks for caring eslint issues :-)

**Comment by guido4096** [comment]
Hi @LucasBrazi06, is there still something I should do on this mergerequest? I might be missing some action in github

**Comment by LucasBrazi06** [comment]
@guido4096 I assume that you have done with the changes (Total amps + amps/phase), right?
If yes, your PR is in 'Requested changes' pipeline and should be in the 'To be reviewed' one.
We use ZenHub in Kanban mode.
Let me know.

**Comment by guido4096** [comment]
> @guido4096 I assume that you have done with the changes (Total amps + amps/phase), right? If yes, your PR is in 'Requested changes' pipeline and should be in the 'To be reviewed' one. We use ZenHub in Kanban mode. Let me know.
@LucasBrazi06, I would want to move it to a different stage, but I believe I have no rights to do so? Or I miss something else.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06, I would want to move it to a different stage, but I believe I have no rights to do so? Or I miss something else.

What do you mean by 'move it to a different stage'?

**Comment by guido4096** [comment]
I mean, how to get the PR in the 'To be reviewed' pipeline? I've been trying all over and I miss how to to do this. Or maybe I should not be doing this, but somebody else?

**Comment by LucasBrazi06** [comment]
> I mean, how to get the PR in the 'To be reviewed' pipeline? I've been trying all over and I miss how to to do this. Or maybe I should not be doing this, but somebody else?

Ah ok, I think you'll have to install the ZenHub plugin in your browser or use the ZenHub dashboard:
https://app.zenhub.com/workspaces/sap-labs-france-5dfcfa78b123df328c12f43d/board

Or in the repo itself:

**Comment by guido4096** [comment]
I did, but there the ZenHub board says it is read-only. See sreenshot, the notice at the bottom.
image

**Comment by LucasBrazi06** [comment]
Weird!!!
Check this link:
https://app.zenhub.com/workspaces/sap-labs-france-5dfcfa78b123df328c12f43d/board?invite=true

**Comment by guido4096** [comment]
sorry, still the same: 
image

I think I need write access to the repository?
image

**Comment by LucasBrazi06** [comment]
You're right, my bad, the repos of the team were read-only :-(.
I just changed them to write:

You should have access now.
Let me know.

**Comment by LucasBrazi06** [comment]
> Well, I can edit now in Github itself, but the ZenHub is still read-only. I'm a bit concerned that maybe you openend up github repo now to write for everybody?
> 
> I'm not a github expert, but maybe I need to be added as a member?

Write permission is only to the team named Contributor to which you belong, so it should be okay.

**Comment by guido4096** [comment]
it works now! Maybe some syncing was needed to get the settings into zenhub? Moved the PR

**Comment by LucasBrazi06** [comment]
FYI, I'll connect this PR to its issue:

**Review by LucasBrazi06 — APPROVED** [review]

**Pull request merged**
