### PR TITLE
Xsenv integration

### PR DESCRIPTION
**Pull request by captaineaglex**
I have added node module @sap/xsenv and its type for interacting xsuaa JWT. 

In src/app/authentication/login/authentication-login.component.ts  file,

Just to show the build error I have, I have written a line that uses a function from @sap/xsenv module. This function prints the JWT details that have been forwarded by app router. (my aim is to implement in that section, if valid JWT exists then SSO, if not then land on application authentication page as we do normally).

But in the build phase, I have the following errors:

Field 'browser' doesn't contain a valid alias configuration

Error: ./node_modules/@sap/xsenv/lib/k8sservice.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\I068050\Desktop\Customers\SAP_Labs\evse_modules\ev-dashboard\node_modules\@sap\xsenv\lib'

Error: ./node_modules/@sap/xsenv/lib/cacert.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\I068050\Desktop\Customers\SAP_Labs\evse_modules\ev-dashboard\node_modules\@sap\xsenv\lib'

Error: ./node_modules/@sap/xsenv/node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\I068050\Desktop\Customers\SAP_Labs\evse_modules\ev-dashboard\node_modules\@sap\xsenv\node_modules\assert-plus'

I have researched a lot this issue. My conclusion is that this is Angular relevant. (https://github.com/angular/angular-cli/issues/10681). 

I have tried a couple of workarounds to fix in package.json, but with no luck. Hence, I wanted to try some customization on webpack.config.js.  Before extending the configuration for angular in our dashboard, I want to clarify with you.

### CODE REVIEW

**Comment by LucasBrazi06** [comment]
@captaineaglex Why are you not addressing this issue in the @sap/xsenv repository?
They should provide you support for the integration with Angular I think.

**Comment by captaineaglex** [comment]
@LucasBrazi06 : I am sorry but I am not sure how I can do that. Do you mean reporting an issue in npmjs.org? I couldn't find the repository itself where I can address this issue.

**Comment by LucasBrazi06** [comment]
> I have added node module @sap/xsenv and its type for interacting xsuaa JWT.

I was talking about the module you added (@sap/xsenv) which is not working with Angular, this is where to report the issue.
Or am I misunderstanding something here?

**Comment by captaineaglex** [comment]
well, there are two questions marks on my side:
1.  I dont know the counter part to report an issue on @sap/xsenv module. :( Sorry about it.

2. The errors received are not spesific to @sap/xsenv module. I have read that some other modules when used with certain Angular versions, fall into these errors as well. That's why I think using a method which worked for other modules, might work in our case as well.

**Comment by jerome-benoit** [comment]
> 
> @LucasBrazi06 <https://github.com/LucasBrazi06> : I am sorry but I am not sure how I can do that. Do you mean reporting an issue in npmjs.org? I couldn't find the repository itself where I can address this issue.
> 
> 

You can report the issue directly upstream: find the main repository used to develop the npm package and open an issue here. You can also have a look first at existing issues to see if it has been already reported.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by jerome-benoit** [comment]
Closing, an alternate solution was found.

**Pull request closed without merging**
