### PR TITLE
billing - settings - change the order of stripe fields to avoid unwan…

### PR DESCRIPTION
**Pull request by ClaudeROSSI**
billing - settings - change the order of stripe fields to avoid unwanted chrome autocomplete features

### CODE REVIEW

**Comment by ClaudeROSSI** [comment]
Does not work as expected ...

@cabch, @mahdibenromdhane : I need your advise

**Comment by ClaudeROSSI** [comment]
The change I have done is simply to make sure the input fields do not get populated with the user name and regular user password when opening the Billing settings. This to prevent a confusing behavior.

However, I couldn't find any option to prevent chrome from considering the STRIPE settings as providing user/password information.
The side-effect (at least on my machine) is that chrome keep asking the user whether he/she wants to save the new user/password.
This is an issue because the public_key and the secret_key is then somehow persisted client side.

**Comment by LucasBrazi06** [comment]
> The change I have done is simply to make sure the input fields do not get populated with the user name and regular user password when opening the Billing settings. This to prevent a confusing behavior.
> 
> However, I couldn't find any option to prevent chrome from considering the STRIPE settings as providing user/password information.
> The side-effect (at least on my machine) is that chrome keep asking the user whether he/she wants to save the new user/password.
> This is an issue because the public_key and the secret_key is then somehow persisted client side.

You need to show me ;-)

**Comment by ClaudeROSSI** [comment]
> > The change I have done is simply to make sure the input fields do not get populated with the user name and regular user password when opening the Billing settings. This to prevent a confusing behavior.
> > However, I couldn't find any option to prevent chrome from considering the STRIPE settings as providing user/password information.
> > The side-effect (at least on my machine) is that chrome keep asking the user whether he/she wants to save the new user/password.
> > This is an issue because the public_key and the secret_key is then somehow persisted client side.
> 
> You need to show me ;-)

Actually the change do not work. For some reasons Chrome ignores the settings!
I get a popup to save the secret_key as my new password each time i change one of the property of the billings settings form!
This is crazy!

**Comment by ClaudeROSSI** [comment]
We need to find another solution ... putting it back to in progress

**Pull request closed without merging**
